# Generated by Django 6.0 on 2026-05-13 21:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('posicion', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera Base'), ('2B', 'Segunda Base'), ('3B', 'Tercera Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter')], max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('biografia', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('altura', models.CharField(blank=True, max_length=20)),
                ('peso', models.CharField(blank=True, max_length=20)),
                ('bateo', models.CharField(blank=True, max_length=10)),
                ('lanzamiento', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('destacada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('carreras_local', models.IntegerField(default=0)),
                ('carreras_visitante', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('pospuesto', 'Pospuesto'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('estadio', models.CharField(blank=True, max_length=200)),
                ('temporada', models.CharField(max_length=20)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='equipo.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='equipo.equipo')),
            ],
            options={
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('preferente', 'Preferente'), ('vip', 'VIP'), ('palco', 'Palco')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('seccion', models.CharField(blank=True, max_length=50)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='equipo.partido')),
            ],
            options={
                'verbose_name_plural': 'Boletos',
            },
        ),
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=20)),
                ('juegos_jugados', models.IntegerField(default=0)),
                ('ganados', models.IntegerField(default=0)),
                ('perdidos', models.IntegerField(default=0)),
                ('porcentaje', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('carreras_favor', models.IntegerField(default=0)),
                ('carreras_contra', models.IntegerField(default=0)),
                ('racha', models.CharField(blank=True, max_length=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
            options={
                'verbose_name_plural': 'Tabla de Posiciones',
                'ordering': ['-porcentaje', '-ganados'],
            },
        ),
    ]
