# Generated by Django 5.2.13 on 2026-05-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('titulo_linea1', models.CharField(max_length=200, verbose_name='Título línea 1')),
                ('titulo_linea2', models.CharField(blank=True, max_length=200, verbose_name='Título línea 2')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Imagen (sube aquí)')),
                ('imagen_url', models.URLField(blank=True, help_text='Se usa si no subes imagen', verbose_name='URL de imagen externa')),
                ('btn1_texto', models.CharField(blank=True, max_length=100, verbose_name='Botón 1 texto')),
                ('btn1_url', models.CharField(blank=True, max_length=200, verbose_name='Botón 1 enlace')),
                ('btn2_texto', models.CharField(blank=True, max_length=100, verbose_name='Botón 2 texto')),
                ('btn2_url', models.CharField(blank=True, max_length=200, verbose_name='Botón 2 enlace')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Diapositiva Hero',
                'verbose_name_plural': 'Diapositivas Hero',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes (FAQ)',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='patrocinadores/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='Enlace web')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='destacado_inicio',
            field=models.BooleanField(default=False, help_text='Mostrar este jugador en la sección destacada del inicio', verbose_name='Destacar en inicio'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio actual')),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio anterior (tachado)')),
                ('badge', models.CharField(blank=True, choices=[('', 'Sin etiqueta'), ('sale', 'Oferta'), ('new', 'Nuevo'), ('sold', 'Agotado')], max_length=10, verbose_name='Etiqueta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en el carrusel de tienda del inicio', verbose_name='Destacado en inicio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.categoriaproducto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
