# Generated by Django 6.0 on 2026-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_categoriaproducto_heroslide_itemfaq_patrocinador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('texto', 'Solo Texto'), ('imagen', 'Con Imagen')], default='texto', max_length=10, verbose_name='Tipo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagen')),
                ('enlace', models.CharField(blank=True, max_length=200, verbose_name='Enlace')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destacado_grid', models.BooleanField(default=False, help_text='Mostrar en la sección de noticias del inicio', verbose_name='Mostrar en News Grid')),
            ],
            options={
                'verbose_name': 'Artículo de Noticia',
                'verbose_name_plural': 'Artículos de Noticias (News Grid)',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='instagram/', verbose_name='Imagen')),
                ('enlace', models.URLField(blank=True, verbose_name='Enlace a Instagram')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen de Instagram',
                'verbose_name_plural': 'Imágenes de Instagram',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la habilidad')),
                ('porcentaje', models.PositiveIntegerField(default=0, help_text='Valor entre 0 y 100', verbose_name='Porcentaje (0-100)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Barra de Progreso',
                'verbose_name_plural': 'Barras de Progreso (Skills)',
                'ordering': ['orden'],
            },
        ),
    ]
