# Generated by Django 6.0 on 2026-05-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_articulonoticia_imageninstagram_skillprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageninstagram',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa si no subes imagen', verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='imageninstagram',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/', verbose_name='Imagen'),
        ),
    ]
