# Generated by Django 6.0 on 2026-05-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='imagen',
            field=models.ImageField(default=1, upload_to='hero/', verbose_name='Imagen (sube aquí)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='titulo_linea1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título línea 1'),
        ),
    ]
