# Generated by Django 6.0 on 2026-05-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0008_pais_estado_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar como el próximo partido a mostrar en la página de inicio', verbose_name='Próximo partido destacado'),
        ),
    ]
