# Generated by Django 6.0 on 2026-05-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0009_partido_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la sección de próximo partido', null=True, upload_to='partidos/', verbose_name='Imagen de fondo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='opacidad_overlay',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='Opacidad del overlay oscuro (0.00 = transparente, 1.00 = opaco)', max_digits=3, verbose_name='Opacidad del overlay'),
        ),
    ]
