# Generated by Django 6.0 on 2026-05-16 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0010_partido_imagen_fondo_partido_opacidad_overlay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='equipo.ciudad', verbose_name='Ciudad'),
        ),
    ]
