# Generated by Django 6.0 on 2026-05-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0011_cambiar_ciudad_a_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
