# Generated by Django 6.0 on 2026-05-18 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0012_noticia_activo_noticia_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximoJuegoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('subtitulo', models.CharField(default='LO QUE ESTÁ EN TENDENCIA', max_length=200, verbose_name='Subtítulo')),
                ('titulo', models.CharField(default='PRÓXIMO JUEGO', max_length=200, verbose_name='Título')),
                ('texto_personalizado', models.CharField(blank=True, help_text='Opcional: texto en lugar de mostrar equipos del partido', max_length=300, verbose_name='Texto personalizado')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='proximo_juego/', verbose_name='Imagen de fondo')),
                ('opacidad_overlay', models.DecimalField(decimal_places=2, default=0.7, help_text='0.00 = transparente, 1.00 = completamente opaco', max_digits=3, verbose_name='Opacidad del overlay')),
                ('texto_boton', models.CharField(default='COMPRAR BOLETOS', max_length=100, verbose_name='Texto del botón')),
                ('url_boton', models.URLField(default='https://arema.mx/e/17890', verbose_name='URL del botón')),
                ('mostrar_countdown', models.BooleanField(default=True, verbose_name='Mostrar contador regresivo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Próximo Juego Destacado',
                'verbose_name_plural': 'Próximos Juegos Destacados',
                'ordering': ['-activo', 'orden'],
            },
        ),
    ]
