# Generated by Django 6.0 on 2026-05-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0013_proximojuegodestacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(default='Calendario', help_text='Solo para identificación en el panel', max_length=200, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='calendario_overlay/', verbose_name='Imagen del overlay')),
                ('url_destino', models.URLField(blank=True, help_text='Opcional: URL a la que redirige al hacer clic', verbose_name='URL de destino')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Overlay de Calendario',
                'verbose_name_plural': 'Overlays de Calendario',
                'ordering': ['-activo', 'orden'],
            },
        ),
    ]
