# Generated by Django 6.0 on 2026-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0014_calendariooverlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='moneda',
            field=models.CharField(
                choices=[('MXN', 'Peso mexicano (MXN)'), ('USD', 'Dólar (USD)')],
                default='MXN',
                max_length=3,
                verbose_name='Moneda',
            ),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo_cambio',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text='Se usa para convertir entre MXN y USD. Ejemplo: 18.5000',
                max_digits=12,
                null=True,
                verbose_name='Tipo de cambio (MXN por 1 USD)',
            ),
        ),
    ]
